version: '3.8'

services:
    jwt-auth:
        build: ./jwt-auth
        ports:
            - 8000:8000
        environment: 
            MONGODB_URL: ${MONGODB_URL}
            JWT_ACCESS_KEY: ${JWT_ACCESS_KEY}
            JWT_REFRESH_KEY: ${JWT_REFRESH_KEY}

    redis:
        image: redis
        ports:
            - 6379:6379